-- Basic
require('core.plugins')
require('core.mappings')
require('core.theme')
require('core.configs')
-- require('core.colors')
-- Plugins
require('plugins.neotree')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.mason')
require('plugins.telescope')
require('plugins.nullls')
require('plugins.autopairs')
require('plugins.autotag')
require('plugins.buffline')
require('plugins.comments')
require('plugins.dashboard') 
require('plugins.gitsigns') 
require('plugins.hop') 
require('plugins.lualine') 
require('plugins.toggleterm') 
require('plugins.whichkey') 
